// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClc93C3ChUeZfn2puFZWMvnLWGl4dRVCg',
    appId: '1:248627898906:web:c9749f382f6feb94243fa3',
    messagingSenderId: '248627898906',
    projectId: 'starter-app-b511e',
    authDomain: 'starter-app-b511e.firebaseapp.com',
    storageBucket: 'starter-app-b511e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_g0Cks9mjhROhXO4fVkoKka48y416PU',
    appId: '1:248627898906:android:8a0730c3191d079a243fa3',
    messagingSenderId: '248627898906',
    projectId: 'starter-app-b511e',
    storageBucket: 'starter-app-b511e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHdhXHued_Gk80hL1LiHv-GuDHrIWOwhw',
    appId: '1:248627898906:ios:c3c96ca100517b26243fa3',
    messagingSenderId: '248627898906',
    projectId: 'starter-app-b511e',
    storageBucket: 'starter-app-b511e.appspot.com',
    iosClientId: '248627898906-dldagumvo327df1cgs4nkq17le1kemas.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHdhXHued_Gk80hL1LiHv-GuDHrIWOwhw',
    appId: '1:248627898906:ios:c3c96ca100517b26243fa3',
    messagingSenderId: '248627898906',
    projectId: 'starter-app-b511e',
    storageBucket: 'starter-app-b511e.appspot.com',
    iosClientId: '248627898906-dldagumvo327df1cgs4nkq17le1kemas.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkgpt',
  );
}
